# Importing required libraries

In [34]:
import warnings
warnings.filterwarnings('ignore')
import os
import cv2
import numpy as np
from skimage.feature import hog
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from sklearn.model_selection import GridSearchCV

# Loading, Preprocessing, Normalizing, Data augmentaion and Feature extraction

In [2]:
def load_and_normalize_image(path):
    img = cv2.imread(path)
    if img is None:
        raise ValueError(f"Image cannot be read. Check the file format and path: {path}")
    img = cv2.resize(img, (256, 256))
    img = img.astype(np.float32) / 255.0
    return img

def extract_hog_features(image):
    features, hog_image = hog(image, orientations=8, pixels_per_cell=(16, 16),
                              cells_per_block=(1, 1), visualize=True, channel_axis=-1)
    return features

def augment_image(image):
    rotated = cv2.rotate(image, cv2.ROTATE_90_CLOCKWISE)
    flipped = cv2.flip(image, 1)
    return rotated, flipped

def prepare_dataset(base_directory):
    features = []
    labels = []
    supported_formats = ('.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.tif')  # Add or remove formats as needed

    # Debugging to check the path
    print(f"Base directory: {base_directory}")
    print(f"Directories in base directory: {os.listdir(base_directory)}")

    for label_dir in os.listdir(base_directory):
        class_dir = os.path.join(base_directory, label_dir)
        if os.path.isdir(class_dir):  # Check if it is a directory
            print(f"Processing folder: {label_dir}")
            for filename in os.listdir(class_dir):
                if filename.lower().endswith(supported_formats):  # Checking against supported formats
                    path = os.path.join(class_dir, filename)
                    print(f"Processing file: {filename}")
                    try:
                        img = load_and_normalize_image(path)
                        img_features = extract_hog_features(img)
                        features.append(img_features)
                        labels.append(label_dir)  # Using folder name as label

                        # Data augmentation
                        rotated, flipped = augment_image(img)
                        features.append(extract_hog_features(rotated))
                        labels.append(label_dir)
                        features.append(extract_hog_features(flipped))
                        labels.append(label_dir)
                    except Exception as e:
                        print(f"Error processing {filename}: {e}")
        else:
            print(f"Skipped: {label_dir} is not a directory")

    return np.array(features), labels


# Loading the data

In [3]:
# Assuming the base directory is the path to the parent folder containing all class folders
folder_path = r"C:\Users\Kusha\Desktop\masters\final_sem\project\final_data"
features, labels = prepare_dataset(folder_path)

Base directory: C:\Users\Kusha\Desktop\masters\final_sem\project\final_data
Directories in base directory: ['byes', 'four', 'leg_byes', 'not_out', 'no_action', 'no_ball', 'out', 'six', 'wide']
Processing folder: byes
Processing file: byes 1.jpg
Processing file: byes 1.png
Processing file: byes 2.jpg
Processing file: byes 2.png
Processing file: byes 3.jpg
Processing file: byes 5.jpg
Processing file: byes-1.jpg
Processing file: byes-10.jpg
Processing file: byes-11.jpg
Processing file: byes-12.jpg
Processing file: byes-13.jpg
Processing file: byes-14.jpg
Processing file: byes-15.jpg
Processing file: byes-16.jpg
Processing file: byes-17.jpg
Processing file: byes-18.jpg
Processing file: byes-19.jpg
Processing file: byes-2.jpg
Processing file: byes-20.jpeg
Processing file: byes-21.jpeg
Processing file: byes-22.jpeg
Processing file: byes-3.jpg
Processing file: byes-4.jpg
Processing file: byes-5.jpg
Processing file: byes-6.jpg
Processing file: byes-7.jpg
Processing file: byes-8.jpg
Processing 

Processing file: dreamstimemaximum_93198367.jpg
Processing file: no out 2.jpeg
Processing file: Noball.jpg
Processing file: Noball_1.jpg
Processing file: Noball_2.jpg
Processing file: noball_3.jpg
Processing file: noball_4.jpg
Processing file: not out 1.jpeg
Processing file: not out 10.png
Processing file: not out 11.png
Processing file: not out 12.png
Processing file: not out 13.png
Processing file: not out 14.png
Processing file: not out 15.png
Processing file: not out 16.png
Processing file: not out 17.png
Processing file: not out 18.png
Processing file: not out 19.png
Processing file: not out 20.png
Processing file: not out 21.png
Processing file: not out 22.png
Processing file: not out 23.png
Processing file: not out 24.png
Processing file: not out 3.png
Processing file: not out 4.png
Processing file: not out 5.png
Processing file: not out 6.png
Processing file: not out 7.png
Processing file: not out 8.png
Processing file: not out 9.png
Processing file: notout.jpg
Processing file:

Processing file: k31.jpg
Processing file: k32.jpg
Processing file: k33.jpg
Processing file: k34.jpg
Processing file: k35.jpg
Processing file: k36.jpg
Processing file: k37.jpg
Processing file: k38.jpg
Processing file: k39.jpg
Processing file: k40.jpg
Processing file: k41.jpg
Processing file: k42.jpg
Processing file: k43.jpg
Processing file: k44.jpg
Processing file: k45.jpg
Processing file: k46.jpg
Processing file: k5.jpg
Processing file: k6.jpeg
Processing file: k7.jpg
Processing file: k8.jpg
Processing file: k9.jpg
Processing file: maxresdefault.jpg
Processing file: no bal 21.png
Processing file: no bal 59.png
Processing file: no ball 1.jpg
Processing file: no ball 10.jpg
Processing file: no ball 11.jpg
Processing file: no ball 12.jpg
Processing file: no ball 13.jpg
Processing file: no ball 14.jpg
Processing file: no ball 15.jpeg
Processing file: no ball 15.jpg
Processing file: no ball 16.jpg
Processing file: no ball 17.jpeg
Processing file: no ball 17.jpg
Processing file: no ball 17.p

Processing file: Screenshot (569).png
Processing file: Screenshot (575).png
Processing file: Screenshot (576).png
Processing file: Screenshot (577).png
Processing file: Screenshot (578).png
Processing file: Screenshot (583).png
Processing file: Screenshot (601).png
Processing file: Screenshot (602).png
Processing file: Screenshot (603).png
Processing file: Screenshot (611).png
Processing file: Screenshot (612).png
Processing file: Shutterstock_10319120o.jpg
Processing file: umpire_107.jpg
Processing file: umpire_118.jpg
Processing file: umpire_13.jpg
Processing file: umpire_135.jpg
Processing file: umpire_17.jpg
Processing file: umpire_174.jpg
Processing file: umpire_19.jpg
Processing file: umpire_199.jpg
Processing file: umpire_203.jpg
Processing file: umpire_205.jpg
Processing file: umpire_213.jpg
Processing file: umpire_218.jpg
Processing file: umpire_229.jpg
Processing file: umpire_230.jpg
Processing file: umpire_26.jpg
Processing file: umpire_261.jpg
Processing file: umpire_286.jp

Processing file: 101 six.jpg
Processing file: 102 six.jpg
Processing file: 10280_D3_Sixes.jpg
Processing file: 103 six.jpg
Processing file: 104 six.jpg
Processing file: 105 six.jpg
Processing file: 106 six.jpg
Processing file: 107 six.jpg
Processing file: 108 six.jpg
Processing file: 109 six.jpg
Processing file: 11 six.jpg
Processing file: 110 six.jpg
Processing file: 111 six.jpg
Processing file: 112 six.jpg
Processing file: 113 six.jpg
Processing file: 114 six.jpg
Processing file: 115 six.jpg
Processing file: 1155-six.jpg
Processing file: 116 six.jpg
Processing file: 117 six.jpg
Processing file: 118 six.jpg
Processing file: 119 six.jpg
Processing file: 12 six.jpg
Processing file: 120 six.png
Processing file: 121 six.png
Processing file: 122 six.png
Processing file: 123 six.png
Processing file: 124 six.png
Processing file: 125 six.png
Processing file: 126 six.png
Processing file: 127 six.png
Processing file: 128 six.png
Processing file: 129 six.png
Processing file: 13 six.jpg
Processin

Processing file: o16.jpg
Processing file: o18.jpg
Processing file: o19.jpg
Processing file: o2.jpeg
Processing file: o20.jpg
Processing file: o21.jpg
Processing file: o22.jpg
Processing file: o23.jpg
Processing file: o24.jpg
Processing file: o25.jpg
Processing file: o26.jpg
Processing file: o27.jpg
Processing file: o28.jpg
Processing file: o29.jpg
Processing file: o3.jpg
Processing file: o30.jpg
Processing file: o31.jpg
Processing file: o32.jpg
Processing file: o33.jpg
Processing file: o34.jpg
Processing file: o35.jpg
Processing file: o36.jpg
Processing file: o37.jpg
Processing file: o38.jpg
Processing file: o39.jpg
Processing file: o4.jpg
Processing file: o40.jpg
Processing file: o41.jpg
Processing file: o43.jpg
Processing file: o44.jpg
Processing file: o45.jpg
Processing file: o47.jpg
Processing file: o48.jpg
Processing file: o49.jpg
Processing file: o50.jpg
Processing file: o51.jpg
Processing file: o52.jpg
Processing file: o53.jpg
Processing file: o54.jpg
Processing file: o55.jpg
Pr

Processing file: o13.jpg
Processing file: o14.jpg
Processing file: o15.jpg
Processing file: o16.jpg
Processing file: o19.jpg
Processing file: o2.jpg
Processing file: o20.jpg
Processing file: o22.jpg
Processing file: o23.jpg
Processing file: o24.jpg
Processing file: o25.jpg
Processing file: o26.jpg
Processing file: o27.jpg
Processing file: o28.jpg
Processing file: o29.jpg
Processing file: o3.jpg
Processing file: o30.jpg
Processing file: o31.jpg
Processing file: o32.jpg
Processing file: o33.jpg
Processing file: o34.jpg
Processing file: o35.jpg
Processing file: o356.jpg
Processing file: o37.jpg
Processing file: o38.jpg
Processing file: o4.jpg
Processing file: o40.jpg
Processing file: o41.jpg
Processing file: o42.jpg
Processing file: o43.jpg
Processing file: o5.jpg
Processing file: o6.jpg
Processing file: o7.jpg
Processing file: o8.jpg
Processing file: o9.jpg
Processing file: p03e3a7a.jpg
Processing file: post_image_1feaa23.jpg
Processing file: post_image_fc7ded2.jpg
Processing file: Scree

Processing file: wide_23.jpg
Processing file: wide_24.jpg
Processing file: wide_25.jpg
Processing file: wide_26.jpg
Processing file: wide_27.jpg
Processing file: wide_28.jpg
Processing file: wide_29.jpg
Processing file: wide_3.jpg
Processing file: wide_30.jpg
Processing file: wide_31.jpg
Processing file: wide_32.jpg
Processing file: wide_33.jpg
Processing file: wide_34.jpg
Processing file: wide_35.jpg
Processing file: wide_36.jpg
Processing file: wide_37.jpg
Processing file: wide_38.jpg
Processing file: wide_39.jpg
Processing file: wide_4.jpg
Processing file: wide_40.jpg
Processing file: wide_41.jpg
Processing file: wide_42.jpg
Processing file: wide_44.jpg
Processing file: wide_46.jpg
Processing file: wide_47.jpg
Processing file: wide_48.jpg
Processing file: wide_49.jpg
Processing file: wide_5.jpg
Processing file: wide_50.jpg
Processing file: wide_52.jpg
Processing file: wide_53.jpg
Processing file: wide_54.jpg
Processing file: wide_55.jpg
Processing file: wide_56.jpg
Processing file: 

In [38]:
len(features[0])

2048

In [4]:
features

[array([0.40557173, 0.40557173, 0.40557173, ..., 0.38674006, 0.1882625 ,
        0.10783581], dtype=float32),
 array([0.6826914 , 0.1967573 , 0.02451483, ..., 0.08195703, 0.0803697 ,
        0.15195051], dtype=float32),
 array([0.6663567 , 0.02807274, 0.00375269, ..., 0.12733564, 0.05305334,
        0.00560475], dtype=float32),
 array([0.01737675, 0.        , 0.10927945, ..., 0.411702  , 0.39343727,
        0.29742244], dtype=float32),
 array([0.45745304, 0.05209549, 0.25536785, ..., 0.27054337, 0.18449545,
        0.24647458], dtype=float32),
 array([0.4098983 , 0.29189342, 0.4098983 , ..., 0.48601815, 0.48601815,
        0.25316712], dtype=float32),
 array([0.46527904, 0.21373479, 0.24757114, ..., 0.22175895, 0.33794287,
        0.4058216 ], dtype=float32),
 array([0.42182985, 0.22306652, 0.37007928, ..., 0.3593345 , 0.32659394,
        0.3593345 ], dtype=float32),
 array([0.36211437, 0.33376113, 0.36211437, ..., 0.20676896, 0.24956205,
        0.42004338], dtype=float32),
 array([0.

In [5]:
labels

['byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'byes',
 'four',
 'four',
 'four',
 'four',
 'four',
 'four',
 

In [6]:
unique_values = list(dict.fromkeys(labels))
print(unique_values)

['byes', 'four', 'leg_byes', 'not_out', 'no_action', 'no_ball', 'out', 'six', 'wide']


# Splitting the data into training and testing

In [7]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.3, random_state=42)

In [8]:
X_train

[array([0.41516018, 0.41516018, 0.41516018, ..., 0.08797058, 0.02629871,
        0.01838014], dtype=float32),
 array([0.49735937, 0.49735937, 0.16502637, ..., 0.44391948, 0.22429992,
        0.08069759], dtype=float32),
 array([0.38449654, 0.38449654, 0.38449654, ..., 0.22885491, 0.12446646,
        0.44240838], dtype=float32),
 array([0.35882455, 0.35882455, 0.35882455, ..., 0.22159526, 0.39668968,
        0.07781234], dtype=float32),
 array([0.5489672 , 0.11507268, 0.36914515, ..., 0.39432967, 0.28956163,
        0.13309146], dtype=float32),
 array([0.40386352, 0.40386352, 0.40386352, ..., 0.35355338, 0.35355338,
        0.35355338], dtype=float32),
 array([0.35668758, 0.35668758, 0.35668758, ..., 0.00909349, 0.34525588,
        0.4686159 ], dtype=float32),
 array([0.550781  , 0.02190761, 0.18362354, ..., 0.40333024, 0.14298487,
        0.40333024], dtype=float32),
 array([0.35355338, 0.35355338, 0.35355338, ..., 0.05734407, 0.20370947,
        0.3990017 ], dtype=float32),
 array([0.

In [9]:
X_test

[array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0.38417995, 0.25161135, 0.38417995, ..., 0.42023316, 0.15661964,
        0.01093919], dtype=float32),
 array([0.3649498 , 0.3649498 , 0.3649498 , ..., 0.36755532, 0.36755532,
        0.3647317 ], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0.48045138, 0.25130045, 0.10146124, ..., 0.01477768, 0.02864535,
        0.00417976], dtype=float32),
 array([0.355958  , 0.355958  , 0.355958  , ..., 0.35933134, 0.4355372 ,
        0.33482888], dtype=float32),
 array([0.30675426, 0.22639288, 0.5101465 , ..., 0.38320205, 0.2257679 ,
        0.2607029 ], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0., 0., 0., ..., 0., 0., 0.], dtype=float32),
 array([0.5866943 , 0.34516516, 0.25749433, ..., 0.41496015, 0.15133291,

In [10]:
y_train

['four',
 'no_ball',
 'leg_byes',
 'out',
 'out',
 'byes',
 'wide',
 'not_out',
 'six',
 'four',
 'wide',
 'six',
 'leg_byes',
 'six',
 'no_ball',
 'six',
 'four',
 'six',
 'wide',
 'four',
 'six',
 'wide',
 'wide',
 'out',
 'six',
 'wide',
 'leg_byes',
 'wide',
 'leg_byes',
 'six',
 'wide',
 'wide',
 'six',
 'out',
 'no_ball',
 'no_action',
 'out',
 'six',
 'four',
 'out',
 'out',
 'no_ball',
 'wide',
 'wide',
 'four',
 'no_action',
 'six',
 'wide',
 'no_action',
 'six',
 'wide',
 'no_ball',
 'six',
 'six',
 'six',
 'wide',
 'wide',
 'six',
 'wide',
 'no_ball',
 'six',
 'six',
 'wide',
 'out',
 'six',
 'four',
 'leg_byes',
 'wide',
 'six',
 'wide',
 'wide',
 'six',
 'wide',
 'six',
 'six',
 'no_action',
 'wide',
 'wide',
 'no_ball',
 'six',
 'wide',
 'four',
 'wide',
 'six',
 'wide',
 'not_out',
 'no_ball',
 'out',
 'no_ball',
 'out',
 'four',
 'not_out',
 'four',
 'wide',
 'no_ball',
 'six',
 'six',
 'six',
 'six',
 'wide',
 'byes',
 'four',
 'wide',
 'out',
 'six',
 'byes',
 'wide',

In [11]:
y_test

['six',
 'no_ball',
 'out',
 'wide',
 'six',
 'six',
 'no_ball',
 'six',
 'out',
 'wide',
 'no_action',
 'out',
 'wide',
 'no_ball',
 'out',
 'six',
 'no_ball',
 'byes',
 'six',
 'no_ball',
 'out',
 'four',
 'six',
 'six',
 'wide',
 'wide',
 'byes',
 'no_action',
 'no_ball',
 'out',
 'four',
 'leg_byes',
 'wide',
 'wide',
 'six',
 'wide',
 'out',
 'no_ball',
 'six',
 'six',
 'four',
 'four',
 'no_ball',
 'out',
 'four',
 'wide',
 'six',
 'byes',
 'six',
 'not_out',
 'no_ball',
 'six',
 'no_ball',
 'wide',
 'six',
 'six',
 'wide',
 'no_ball',
 'no_ball',
 'out',
 'no_ball',
 'out',
 'four',
 'out',
 'six',
 'byes',
 'no_ball',
 'four',
 'six',
 'wide',
 'four',
 'not_out',
 'four',
 'no_ball',
 'wide',
 'four',
 'no_action',
 'leg_byes',
 'wide',
 'six',
 'six',
 'wide',
 'no_ball',
 'six',
 'out',
 'out',
 'leg_byes',
 'not_out',
 'six',
 'leg_byes',
 'six',
 'six',
 'six',
 'wide',
 'four',
 'wide',
 'six',
 'wide',
 'wide',
 'wide',
 'no_ball',
 'six',
 'six',
 'six',
 'out',
 'leg_b

# Encode labels as integers

In [12]:
encoder = LabelEncoder()
y_train_encoded = encoder.fit_transform(y_train)
y_test_encoded = encoder.transform(y_test)

In [42]:
y_train

['four',
 'no_ball',
 'leg_byes',
 'out',
 'out',
 'byes',
 'wide',
 'not_out',
 'six',
 'four',
 'wide',
 'six',
 'leg_byes',
 'six',
 'no_ball',
 'six',
 'four',
 'six',
 'wide',
 'four',
 'six',
 'wide',
 'wide',
 'out',
 'six',
 'wide',
 'leg_byes',
 'wide',
 'leg_byes',
 'six',
 'wide',
 'wide',
 'six',
 'out',
 'no_ball',
 'no_action',
 'out',
 'six',
 'four',
 'out',
 'out',
 'no_ball',
 'wide',
 'wide',
 'four',
 'no_action',
 'six',
 'wide',
 'no_action',
 'six',
 'wide',
 'no_ball',
 'six',
 'six',
 'six',
 'wide',
 'wide',
 'six',
 'wide',
 'no_ball',
 'six',
 'six',
 'wide',
 'out',
 'six',
 'four',
 'leg_byes',
 'wide',
 'six',
 'wide',
 'wide',
 'six',
 'wide',
 'six',
 'six',
 'no_action',
 'wide',
 'wide',
 'no_ball',
 'six',
 'wide',
 'four',
 'wide',
 'six',
 'wide',
 'not_out',
 'no_ball',
 'out',
 'no_ball',
 'out',
 'four',
 'not_out',
 'four',
 'wide',
 'no_ball',
 'six',
 'six',
 'six',
 'six',
 'wide',
 'byes',
 'four',
 'wide',
 'out',
 'six',
 'byes',
 'wide',

In [45]:
# Assuming you've already fitted the LabelEncoder to your y_train data
# and encoded both y_train and y_test
# encoder = LabelEncoder()
# y_train_encoded = encoder.fit_transform(y_train)
# y_test_encoded = encoder.transform(y_test)

# Retrieve the mapping from encoded labels back to original labels
label_mapping = {label: original_label for label, original_label in enumerate(encoder.classes_)}

# Print the mapping
print("Label Mapping:")
for label, original_label in label_mapping.items():
    print(f"Encoded Label {label}: {original_label}")

Label Mapping:
Encoded Label 0: byes
Encoded Label 1: four
Encoded Label 2: leg_byes
Encoded Label 3: no_action
Encoded Label 4: no_ball
Encoded Label 5: not_out
Encoded Label 6: out
Encoded Label 7: six
Encoded Label 8: wide


In [ ]:
labels = {
    0 : "byes",
    1 : "four",
    2 : "leg byes",
    3 : "no action",
    4 : "no ball",
    5 : "not out",
    6 : "out",
    7 : "six",
    8 : "wide"
}

In [43]:
y_train_encoded[:100]

array([1, 4, 2, 6, 6, 0, 8, 5, 7, 1, 8, 7, 2, 7, 4, 7, 1, 7, 8, 1, 7, 8,
       8, 6, 7, 8, 2, 8, 2, 7, 8, 8, 7, 6, 4, 3, 6, 7, 1, 6, 6, 4, 8, 8,
       1, 3, 7, 8, 3, 7, 8, 4, 7, 7, 7, 8, 8, 7, 8, 4, 7, 7, 8, 6, 7, 1,
       2, 8, 7, 8, 8, 7, 8, 7, 7, 3, 8, 8, 4, 7, 8, 1, 8, 7, 8, 5, 4, 6,
       4, 6, 1, 5, 1, 8, 4, 7, 7, 7, 7, 8], dtype=int64)

In [14]:
y_test_encoded

array([7, 4, 6, ..., 3, 3, 7])

# Hyperparameter Tuning and  Random forest Model Training

In [15]:
rf = RandomForestClassifier(random_state=42, n_jobs=-1)

params = {
    'max_depth': [2,3,5,10,20],
    'max_features': ['auto', 'sqrt'],
    'min_samples_leaf': [5,10,20,50,100,200],
    'n_estimators': [10,25,30,50,100,200]
}

# Instantiate the grid search model
grid_search_rf= GridSearchCV(estimator=rf,
                           param_grid=params,
                           cv = 4,
                           n_jobs=-1, verbose=1, scoring="accuracy")

# Fit GridSearchCV to the training data
grid_search_rf.fit(X_train, y_train_encoded)

Fitting 4 folds for each of 360 candidates, totalling 1440 fits


GridSearchCV(cv=4, estimator=RandomForestClassifier(n_jobs=-1, random_state=42),
             n_jobs=-1,
             param_grid={'max_depth': [2, 3, 5, 10, 20],
                         'max_features': ['auto', 'sqrt'],
                         'min_samples_leaf': [5, 10, 20, 50, 100, 200],
                         'n_estimators': [10, 25, 30, 50, 100, 200]},
             scoring='accuracy', verbose=1)

# Evaluate Random Forest

In [16]:
rf_best = grid_search_rf.best_estimator_
rf_predictions = rf_best.predict(X_test)

In [17]:
rf_best

RandomForestClassifier(max_depth=20, max_features='auto', min_samples_leaf=5,
                       n_estimators=200, n_jobs=-1, random_state=42)

In [18]:
rf_predictions

array([7, 3, 6, ..., 8, 4, 7], dtype=int64)

In [19]:
print("Random Forest Classification Report:")
print(classification_report(y_test_encoded, rf_predictions))

Random Forest Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.03      0.05        38
           1       1.00      0.44      0.61       139
           2       1.00      0.36      0.53        83
           3       0.76      0.24      0.36       155
           4       0.69      0.56      0.62       264
           5       1.00      0.28      0.43        40
           6       0.80      0.42      0.55       202
           7       0.56      0.92      0.70       432
           8       0.53      0.80      0.64       328

    accuracy                           0.61      1681
   macro avg       0.76      0.45      0.50      1681
weighted avg       0.69      0.61      0.59      1681



# Hyperparameter Tuning and  K-Nearest neighbors Model Training

In [20]:
param_grid_knn = {
    'n_neighbors': [3, 5, 7],
    'weights': ['uniform', 'distance'],
    'algorithm': ['ball_tree', 'kd_tree', 'brute', 'auto'],
    'leaf_size': [10, 30, 50],
    'metric': ['minkowski', 'euclidean', 'manhattan'],
    'p': [1, 2]
}

In [21]:
# Grid search with cross-validation for KNN
grid_search_knn = GridSearchCV(KNeighborsClassifier(), param_grid_knn, cv=3, verbose=2, n_jobs=-1)
grid_search_knn.fit(X_train, y_train_encoded)

Fitting 3 folds for each of 432 candidates, totalling 1296 fits


GridSearchCV(cv=3, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute', 'auto'],
                         'leaf_size': [10, 30, 50],
                         'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             verbose=2)

# Evaluate KNN model

In [22]:
knn_best = grid_search_knn.best_estimator_
knn_predictions = knn_best.predict(X_test)

In [23]:
knn_best

KNeighborsClassifier(algorithm='ball_tree', leaf_size=10, n_neighbors=3, p=1,
                     weights='distance')

In [24]:
knn_predictions

array([7, 6, 6, ..., 8, 3, 7], dtype=int64)

In [25]:
print("KNN Classification Report:")
print(classification_report(y_test_encoded, knn_predictions))

KNN Classification Report:
              precision    recall  f1-score   support

           0       0.54      0.18      0.27        38
           1       0.72      0.60      0.66       139
           2       0.64      0.67      0.65        83
           3       0.36      0.33      0.34       155
           4       0.75      0.56      0.64       264
           5       0.64      0.62      0.63        40
           6       0.47      0.58      0.52       202
           7       0.69      0.85      0.76       432
           8       0.75      0.69      0.72       328

    accuracy                           0.64      1681
   macro avg       0.62      0.57      0.58      1681
weighted avg       0.65      0.64      0.64      1681



# Model Saving

In [ ]:
#Random forest

In [26]:
import pickle

# data is the object you are pickling (e.g., a trained model)
with open('grid_search_rf_1.pkl', 'wb') as file:
    pickle.dump(grid_search_rf, file, protocol=pickle.HIGHEST_PROTOCOL)

In [27]:
with open('grid_search_rf_1.pkl', 'rb') as file:
    data = pickle.load(file)

In [28]:
data.best_estimator_

RandomForestClassifier(max_depth=20, max_features='auto', min_samples_leaf=5,
                       n_estimators=200, n_jobs=-1, random_state=42)

In [ ]:
#Knn

In [29]:
# data is the object you are pickling (e.g., a trained model)
with open('grid_search_knn_1.pkl', 'wb') as file:
    pickle.dump(grid_search_knn, file, protocol=pickle.HIGHEST_PROTOCOL)

In [30]:
with open('grid_search_knn_1.pkl', 'rb') as file:
    data = pickle.load(file)

In [31]:
data.best_estimator_

KNeighborsClassifier(algorithm='ball_tree', leaf_size=10, n_neighbors=3, p=1,
                     weights='distance')